name: Post-commit Checks

on: [push]

jobs:
    Prettier:
        name: Prettier
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: '.'
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Use Node.js v18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install prettier
              run: npm install --save-dev --save-exact prettier
            - name: Install estlint-prettier config
              run: |
                  npm install --save-dev eslint-config-prettier
            - name: Run prettier
              run: npm run prettier:check
            - name: Cleanup
              if: ${{ always() }}
              run: |
                  rm -rf *
                  rm -rf .[^.] .??*

    ESLint:
        name: ESLint
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: '.'
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Use Node.js v18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install ESLint
              run: npm install --save-dev eslint@^8.57.0
            - name: Install ESLint Dependencies
              run: |
                  npm install --save-dev eslint-config-prettier eslint-config-airbnb eslint-config-airbnb-typescript eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-react eslint-plugin-react-hooks eslint-plugin-react-refresh @typescript-eslint/eslint-plugin @typescript-eslint/parser
            - name: Run ESLint
              run: npm run eslint:check
            - name: Cleanup
              if: ${{ always() }}
              run: |
                  rm -rf *
                  rm -rf .[^.] .??*
